version: '3'

volumes:
  authserver-kafka-data:
    driver: local
  authserver-zookeeper-data:
    driver: local

networks:
  broker-net:
    driver: bridge
    name: auth_server_broker_network

services:    
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - authserver-zookeeper-data:/var/lib/zookeeper/data
    networks:
      - broker-net

  kafka-broker:
    image: confluentinc/cp-kafka:7.3.2
    container_name: kafka-broker
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAKFA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1
    volumes:
      - authserver-kafka-data:/var/lib/kafka/data
    networks:
      - broker-net
  
  init-kafka:
    image: confluentinc/cp-kafka:7.3.2
    container_name: topics-creation
    depends_on:
      - kafka-broker
    entrypoint: ['/bin/sh', '-c']
    command: |
      "
      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server kafka-broker:29092 --create --if-not-exists --topic emails-pending-confirmation --replication-factor 1 --partitions 1

      echo -e 'Kafka topics'
      kafka-topics --bootstrap-server kafka-broker:29092 --list
      "
    volumes:
      - authserver-kafka-data:/var/lib/kafka/data
    networks:
      - broker-net
  
  auth-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: authserver-identity-with-mongoDB
    depends_on:
      - init-kafka
    ports:
      - 7173:443
    environment:
      ASPNETCORE_URLS: https://+
      ASPNETCORE_HTTPS_PORT: 7173
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: ${CERTPASSCODE}
    env_file:
      - .env
    volumes:
      - ${APPDATA}\Microsoft\UserSecrets:\root\.microsoft\usersecrets:ro
      - ${USERPROFILE}\.aspnet\https:/https/
    networks:
      - broker-net